Add periodic variable coefficient linear advection equation
ranocha/SummationByPartsOperators.jl pull request #177
Opened 2023-04-05 15:21 UTC by JoshuaLampert

This adds a semidiscretization for the periodic variable coefficient linear advection equation.
Closes #176.

2023-04-05 17:55 UTC, ranocha requested changes
Great, thanks! Did you run it for some non-trivial setup to check whether it works as intended?

2023-04-05 17:55 UTC, ranocha commented on docs/src/introduction.md
> +  [`VariableLinearAdvectionNonperiodicSemidiscretization`](@ref), [`VariableLinearAdvectionPeriodicSemidiscretization`](@ref)
```suggestion
  [`VariableLinearAdvectionPeriodicSemidiscretization`](@ref), [`VariableLinearAdvectionNonperiodicSemidiscretization`](@ref)
```
The periodic case is conceptually simpler, so I would like to present it first.

2023-04-05 18:46 UTC, JoshuaLampert commented
Yes, I performed some tests, e.g. with constant velocity and piecewise constant velocity (mostly because the solution is easy to verify). The solutions seemed to be reasonable. If you have a specific velocity function with corresponding reference solution in mind I'd be happy to test that, as well.

2023-04-06 07:49 UTC, ranocha commented
There seems to be a problem with the error-based step size controller in my setup. Using a fixed step size as in
```julia
sol = solve(ode, SSPRK104(), dt=0.8*D.Δx, adaptive=false, save_everystep=true)
```
works better. Then, you have a discontinuous coefficient, so any standard high-order finite difference method will result in oscillations - in particular at the periodic boundaries, where the mass is concentrated (instead of flowing out of the domain as in the nonperiodic case).

There is also a problem at the discontinuity at zero. Are you sure that your solution is correct? It does not seem to conserve the total mass $\int u$.

2023-04-06 07:53 UTC, ranocha commented
You can find a discussion of related issues in the paper "Accuracy of Stable, High-order Finite Difference Methods
for Hyperbolic Systems with Non-smooth Wave Speeds" (https://doi.org/10.1007/s10915-019-01088-w)

2023-04-06 09:16 UTC, JoshuaLampert commented
Thanks for the clarification! I expected the oscillations, but was wondering about the discontinuity at 0. I naively assumed the analytical solution would be the same for a piecewise constant coefficient as for a constant one, but you're right. It doesn't conserve the total mass.
So this is fine, I guess?

2023-04-06 10:16 UTC, ranocha commented
Yes. Let's go ahead and merge this PR. Thanks!

2023-04-06 10:52 UTC, merged