Create FormatCheck.yml
ranocha/SummationByPartsOperators.jl pull request #283
Opened 2024-08-01 08:24 UTC by ranocha

2025-03-17 18:11 UTC, JoshuaLampert commented
What's the status with this PR? I think it would be good to have the code formatted with JuliaFormatter.jl. I can help if needed.

2025-03-18 05:44 UTC, ranocha commented
The issue is that this requires a lot of changes to be reviewed. It would be great if you would like to help me with that.

2025-03-18 10:52 UTC, JoshuaLampert requested changes
IMHO, most weird formatting is in the `dev/` directory. Of course there are lots of changes especially in the coefficient files and some manual formatting got lost, but overall I think the `src/` folder looks mostly fine (modulo the known issues with the formatter like missing white spaces around operators in macros and weird linebreaks sometimes).

2025-03-18 12:43 UTC, ranocha commented
Thanks a lot! I decided to remove the `dev` folder from the formatter.

2025-03-18 12:48 UTC, JoshuaLampert approved these changes

2025-03-18 14:56 UTC, merged